version: '3.9'

services:
  knightschallenge.webapi:
    build: ../backend/KnightsChallenge.WebApi
    ports:
      - 80:8080
    restart: always
    depends_on:
      - rabbitmq
      - mongodb
      - aspire 
    links:
      - rabbitmq
      - mongodb
      - aspire
    environment:
      MONGO_DB_CONNECTION_URI: mongodb://username:password@mongodb:27017/
      MONGO_DB_CONNECTION_DATABASE: knightsservice
      RABBITMQ_HOSTNAME: rabbitmq
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      OTEL_EXPORTER_OTLP_ENDPOINT: http://aspire:4317
      OTEL_SERVICE_NAME: KnightsChallengeService
      OTEL_METRIC_EXPORT_INTERVAL: 5000
  
  knightschallenge.webapp:
    build: ../frontend
    ports:
      - 3000:80
    depends_on:
      - knightschallenge.webapi
    links:
      - knightschallenge.webapi
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      VITE_WEB_API_URI: http://knightschallenge.webapi
  
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672
      
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: entrypoint
    volumes:
      - ./mongodb/initdb.js:/docker-entrypoint-initdb.d/initdb.js:ro
  
  aspire:
    image: mcr.microsoft.com/dotnet/nightly/aspire-dashboard:8.0.0-preview.6
    ports:
      - 18888:18888
      - 4317:18889
        
networks:
  knights:
    driver: bridge
    name: knights