version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672
      
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: entrypoint
    volumes:
      - ./mongodb/initdb.js:/docker-entrypoint-initdb.d/initdb.js:ro
  
  aspire:
    image: mcr.microsoft.com/dotnet/nightly/aspire-dashboard:8.0.0-preview.6
    ports:
      - 18888:18888
      - 4317:18889
        
networks:
  knights:
    driver: bridge
    name: knights